- name: Blue Sky
  entities:
    group.all_lights:
      state: on
      rgb_color: [0,0,255]
      brightness: 255
      white_value: 60
    light.hyperion:
      state: on
      effect: "Rainbow swirl fast"

- name: Rainbows
  entities:
    group.all_lights:
      state: on
      effect: "rainbow"
    light.hyperion:
      state: on
      effect: "Blue mood blobs"

- name: Music mode
  entities:
    group.all_lights:
      state: on
      effect: "music"
    light.hyperion:
      state: on
      effect: "Knight rider"

- name: Christmas
  entities:
    light.livingroom_light:
      state: on
      rgb_color: [255,0,0]
      brightness: 255
      white_value: 0
    light.kitchen_light:
      state: on
      rgb_color: [0,255,0]
      brightness: 255
      white_value: 0
    light.prep_light:
      state: on
      rgb_color: [0,0,0]
      brightness: 255
      white_value: 255
    light.office_light:
      state: on
      rgb_color: [0,255,0]
      brightness: 255
      white_value: 0
    light.desk_light:
      state: on
      rgb_color: [255,0,0]
      brightness: 255
      white_value: 0
    light.monitor_light:
      state: on
      rgb_color: [255,0,0]
      brightness: 255
    light.bedroom_light:
      state: on
      rgb_color: [255,0,0]
      brightness: 255
      white_value: 0
    light.closet_light:
      state: on
      rgb_color: [0,255,0]
      brightness: 255
      white_value: 0
    light.bathroom_light:
      state: on
      rgb_color: [0,255,0]
      brightness: 255
      white_value: 0
    light.server_light:
      state: on
      rgb_color: [255,0,0]
      brightness: 255
    light.hyperion:
      state: on
      rgb_color: [0,255,0]
      brightness: 255