# # -1 = NO OVERRIDE
# # 0-X = OVERRIDE ON
# light_rgb_color_r:
#   name: Override Default Red Value for Lights
#   min: -1
#   max: 255
#   step: 5
#   initial: -1
#   mode: slider

# light_rgb_color_g:
#   name: Override Default Green Value for Lights
#   min: -1
#   max: 255
#   step: 5
#   initial: -1
#   mode: slider

# light_rgb_color_b:
#   name: Override Default Blue Value for Lights
#   min: -1
#   max: 255
#   step: 5
#   initial: -1
#   mode: slider

# light_white_value:
#   name: Override Default White Value for Lights
#   min: -1
#   max: 255
#   step: 5
#   initial: -1
#   mode: slider

# light_brightness:
#   name: Override Default Brightness for Lights
#   min: -1
#   max: 255
#   step: 5
#   initial: -1
#   mode: slider

# light_transition:
#   name: Override Default Transition Duration for Lights
#   min: -1
#   max: 20000
#   step: 1
#   initial: -1
#   mode: box

# light_flash:
#   name: Override Default Flash Duration for Lights
#   min: -1
#   max: 25
#   step: 1
#   initial: -1
#   mode: slider

# ## Add local variables here for specific rooms


# ########################
# ## Adapted from https://github.com/master-kenobi/ha-alarmclock
# alarmhour:
#   name: Hour
#   icon: mdi:timer
#   min: 0
#   max: 23
#   step: 1
#   mode: slider
# alarmminutes:
#   name: Minutes
#   icon: mdi:timer
#   min: 0
#   max: 59
#   step: 5
#   mode: slider
# snoozetime:
#   name: Snooze Length
#   icon: mdi:timer
#   min: 5
#   max: 30
#   step: 1
#   mode: slider
# ########################