garrett_tracker:
  name: Track Garrett

special_welcome_home:
  name: Giggity




# ########################
# ## Adapted from https://github.com/master-kenobi/ha-alarmclock
# alarmweekday:
#   name: Weekdays Only
#   icon: mdi:calendar

# alarm_clock_state:
#   name: Alarm Clock

# alarm_clock_snooze:
#   name: Snooze Alarm Clock
# ########################