shower_time:
  alias: Shower Time
  sequence:
    - service: automation.turn_off
      entity_id: automation.turn_off_bathroom_lights
    - delay: '00:20:00'
    - service: automation.turn_on
      entity_id: automation.turn_off_bathroom_lights

all_audio_off:
  alias: Turn Off All Audio
  sequence: 
    - service: media_player.turn_off
      entity_id: media_player.all_speakers
    - service: media_player.turn_off
      entity_id: media_player.speakers
    - service: media_player.turn_off
      entity_id: media_player.assistant_speakers
    - service: media_player.turn_off
      entity_id: media_player.bedoom_speaker
    - service: media_player.turn_off
      entity_id: media_player.living_room_tv
    - service: media_player.turn_off
      entity_id: media_player.office_assistant
    - service: media_player.turn_off
      entity_id: media_player.bathroom_assistant
    - service: media_player.turn_off
      entity_id: media_player.living_room_assistant



