- platform: darksky
  name: "Dark Sky"
  api_key: !secret darksky_key
  latitude: !secret home_lat
  longitude: !secret home_long
  update_interval: "00:02:00"
  monitored_conditions:
    - summary
    - minutely_summary
    - icon
    - apparent_temperature
    - apparent_temperature_max
    - apparent_temperature_min
    - humidity
    - precip_probability
    - precip_intensity
    - precip_type
    - precip_intensity_max
    - wind_speed
    - cloud_cover
    - nearest_storm_distance

# - platform: yr
#   name: Weather
#   forecast: 24
#   monitored_conditions:
#     - temperature
#     - symbol
#     - precipitation
#     - windSpeed
#     - humidity
#     - cloudiness


- platform: deluge
  name: "MasterTower Deluge"
  host: 192.168.0.4
  port: 58846
  username: !secret deluge_user
  password: !secret deluge_pass
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'


- platform: speedtest
  minute:
    - 37
  hour:
    - 2
    # - 6
    # - 9
    # - 12
    # - 15
    # - 19
    # - 21
  monitored_conditions:
    - ping
    - download
    - upload

