sensor:
  # H_8266_1
  - platform: mqtt
    state_topic: "clb/env/H_8266_1/temp"
    name: "H_8266_1 Temp"
    unit_of_measurement: "°C"

  - platform: mqtt
    state_topic: "clb/env/H_8266_1/humid"
    name: "H_8266_1 Humidity"
    unit_of_measurement: "%"

  - platform: mqtt
    state_topic: "clb/lux/H_8266_1/lux"
    name: "H_8266_1 Lux"
    unit_of_measurement: "lux"

  # H_8266_2
  - platform: mqtt
    state_topic: "clb/env/H_8266_2/temp"
    name: "H_8266_2 Temp"
    unit_of_measurement: "°C"

  - platform: mqtt
    state_topic: "clb/env/H_8266_2/humid"
    name: "H_8266_2 Humidity"
    unit_of_measurement: "%"

  # H_8266_3
  - platform: mqtt
    state_topic: "clb/env/H_8266_3/temp"
    name: "H_8266_3 Temp"
    unit_of_measurement: "°C"

  - platform: mqtt
    state_topic: "clb/env/H_8266_3/humid"
    name: "H_8266_3 Humidity"
    unit_of_measurement: "%"

  # N_8266_4
  - platform: mqtt
    state_topic: "clb/sensors/N_8266_4"
    name: "N_8266_4 Temp"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature }}'

  - platform: mqtt
    state_topic: "clb/sensors/N_8266_4"
    name: "N_8266_4 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'

  # N_8266_6
  - platform: mqtt
    state_topic: "clb/sensors/N_8266_6"
    name: "N_8266_6 Temp"
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature }}'

  - platform: mqtt
    state_topic: "clb/sensors/N_8266_6"
    name: "N_8266_6 Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'





binary_sensor:
  # N_8266_1
  - platform: mqtt
    name: "N_8266_1 Motion"
    state_topic: "clb/sensors/N_8266_1"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_2
  - platform: mqtt
    name: "N_8266_2 Motion"
    state_topic: "clb/sensors/N_8266_2"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_3
  - platform: mqtt
    name: "N_8266_3 Motion"
    state_topic: "clb/sensors/N_8266_3"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_4
  - platform: mqtt
    name: "N_8266_4 Motion"
    state_topic: "clb/sensors/N_8266_4"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_5
  - platform: mqtt
    name: "N_8266_5 Motion"
    state_topic: "clb/sensors/N_8266_5"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_6
  - platform: mqtt
    name: "N_8266_6 Motion"
    state_topic: "clb/sensors/N_8266_6"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_7
  - platform: mqtt
    name: "N_8266_7 Motion"
    state_topic: "clb/sensors/N_8266_7"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_8
  - platform: mqtt
    name: "N_8266_8 Motion"
    state_topic: "clb/sensors/N_8266_8"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_9
  - platform: mqtt
    name: "N_8266_9 Motion"
    state_topic: "clb/sensors/N_8266_9"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # N_8266_10
  - platform: mqtt
    name: "N_8266_10 Motion"
    state_topic: "clb/sensors/N_8266_10"
    device_class: motion
    value_template: '{{ value_json.motion }}'

  # S_8285_7
  - platform: mqtt
    name: "S_8285_7 Motion"
    state_topic: "clb/switch/S_8285_7/motion/set/POWER1"
    device_class: motion




switch:
  # H_8266_1
  - platform: mqtt
    name: "H_8266_1 Lux ONOFF"
    command_topic: "clb/lux/H_8266_1/onoff/set"
    state_topic: "clb/lux/H_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "H_8266_1 Env ONOFF"
    command_topic: "clb/env/H_8266_1/onoff/set"
    state_topic: "clb/env/H_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"


  # H_8266_2
  - platform: mqtt
    name: "H_8266_2 Lux ONOFF"
    command_topic: "clb/lux/H_8266_2/onoff/set"
    state_topic: "clb/lux/H_8266_2/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "H_8266_2 Env ONOFF"
    command_topic: "clb/env/H_8266_2/onoff/set"
    state_topic: "clb/env/H_8266_2/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"


  # H_8266_3
  - platform: mqtt
    name: "H_8266_3 Lux ONOFF"
    command_topic: "clb/lux/H_8266_3/onoff/set"
    state_topic: "clb/lux/H_8266_3/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "H_8266_3 Env ONOFF"
    command_topic: "clb/env/H_8266_3/onoff/set"
    state_topic: "clb/env/H_8266_3/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"



  # N_8266_1
  - platform: mqtt
    name: "N_8266_1 Motion ONOFF"
    command_topic: "clb/motion/N_8266_1/onoff/set"
    state_topic: "clb/motion/N_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_1 Lux ONOFF"
    command_topic: "clb/lux/N_8266_1/onoff/set"
    state_topic: "clb/lux/N_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_1 Env ONOFF"
    command_topic: "clb/env/N_8266_1/onoff/set"
    state_topic: "clb/env/N_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"



  # N_8266_2
  - platform: mqtt
    name: "N_8266_2 Motion ONOFF"
    command_topic: "clb/motion/N_8266_2/onoff/set"
    state_topic: "clb/motion/N_8266_2/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_2 Lux ONOFF"
    command_topic: "clb/lux/N_8266_1/onoff/set"
    state_topic: "clb/lux/N_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_2 Env ONOFF"
    command_topic: "clb/env/N_8266_1/onoff/set"
    state_topic: "clb/env/N_8266_1/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  # N_8266_3
  - platform: mqtt
    name: "N_8266_3 Motion ONOFF"
    command_topic: "clb/motion/N_8266_3/onoff/set"
    state_topic: "clb/motion/N_8266_3/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_3 Lux ONOFF"
    command_topic: "clb/lux/N_8266_3/onoff/set"
    state_topic: "clb/lux/N_8266_3/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_3 Env ONOFF"
    command_topic: "clb/env/N_8266_3/onoff/set"
    state_topic: "clb/env/N_8266_3/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  # N_8266_4
  - platform: mqtt
    name: "N_8266_4 Motion ONOFF"
    command_topic: "clb/motion/N_8266_4/onoff/set"
    state_topic: "clb/motion/N_8266_4/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_4 Lux ONOFF"
    command_topic: "clb/lux/N_8266_4/onoff/set"
    state_topic: "clb/lux/N_8266_4/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_4 Env ONOFF"
    command_topic: "clb/env/N_8266_4/onoff/set"
    state_topic: "clb/env/N_8266_4/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  # N_8266_5
  - platform: mqtt
    name: "N_8266_5 Motion ONOFF"
    command_topic: "clb/motion/N_8266_5/onoff/set"
    state_topic: "clb/motion/N_8266_5/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_5 Lux ONOFF"
    command_topic: "clb/lux/N_8266_5/onoff/set"
    state_topic: "clb/lux/N_8266_5/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_5 Env ONOFF"
    command_topic: "clb/env/N_8266_5/onoff/set"
    state_topic: "clb/env/N_8266_5/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  # N_8266_6
  - platform: mqtt
    name: "N_8266_6 Motion ONOFF"
    command_topic: "clb/motion/N_8266_6/onoff/set"
    state_topic: "clb/motion/N_8266_6/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_6 Lux ONOFF"
    command_topic: "clb/lux/N_8266_6/onoff/set"
    state_topic: "clb/lux/N_8266_6/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_6 Env ONOFF"
    command_topic: "clb/env/N_8266_6/onoff/set"
    state_topic: "clb/env/N_8266_6/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  # N_8266_7
  - platform: mqtt
    name: "N_8266_7 Motion ONOFF"
    command_topic: "clb/motion/N_8266_7/onoff/set"
    state_topic: "clb/motion/N_8266_7/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_7 Lux ONOFF"
    command_topic: "clb/lux/N_8266_7/onoff/set"
    state_topic: "clb/lux/N_8266_7/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"

  - platform: mqtt
    name: "N_8266_7 Env ONOFF"
    command_topic: "clb/env/N_8266_7/onoff/set"
    state_topic: "clb/env/N_8266_7/onoff"
    # payload_on: "ON"
    # payload_off: "OFF"
    # availability_topic: "clb/lux/H_8266_1/available"
    # payload_available: "online"
    # payload_not_available: "offline"