################################################
####
#### Welcome Home
#### what do do when a person arrives home
####
################################################


################################################
#
# input_boolean
#
################################################
input_boolean:
  garrett_tracker:
    name: Track Garrett

  special_welcome_home:
    name: Giggity


################################################
#
# automations
#
################################################
automation:
  - id: garrett_tracker_arrive_home
    alias: What to do when Garrett arrives home
    trigger:
      platform: state
      entity_id: group.garrett
      from: 'not_home'
      to: 'home'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.garrett_tracker

  - id: garrett_welcome_home_tts
    alias: Welcome Garrett Home
    trigger:
      platform: state
      entity_id: group.livingroom_motion
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.garrett_tracker
        state: 'on'
    action:
      - service: script.garrett_welcome_home

  # - id: garrett_tracker_leave_home
  #   alias: What to do when Garrett leaves home
  #   trigger:
  #     platform: state
  #     entity_id: group.garrett
  #     from: 'home'
  #     to: 'not_home'
  #   action:
  #     - service: script.garrett_leave_home

################################################
#
# scripts
#
################################################
script:
  garrett_welcome_home:
    alias: Garrett Welcome Home
    sequence:
      - service:  media_player.volume_set
        entity_id: media_player.minispeaker
        data:
          volume_level: .5
      - service: tts.google_say
        entity_id: media_player.minispeaker
        data_template:
          message: >-
            {% if states.input_boolean.special_welcome_home.state == 'on' %}
                {{ [
                "Welcome back to the most magical fucking bachelor pad on the planet",
                "Welcome back. Hi there. If I was a cat I would call you all the time."
                ] | random }}
            {% else %}
              {{ [
              "Hi Garrett, welcome back",
              "Why are you here. Get back to work",
              "Knock knock. Who is there. It is Garrett!",
              "Welcome back Garrett",
              "Hello and welcome back"
              ] | random }}
            {% endif %}
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.garrett_tracker
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.special_welcome_home
      - service: light.turn_on
        data_template:
          entity_id: group.main_room_lights
          effect: "boot_up"
          transition: 1000
          color_temp: "{{ states('sensor.light_color_temp') }}"
          brightness: "{{ states('sensor.light_brightness') }}"


  garrett_leave_home:
    alias: Garrett Leaves Home
    sequence:
      - service: tts.google_say
        entity_id: media_player.minispeaker
        data:
          message: "Goodbye Garrett"
      - delay: '00:15:00'
      - service: light.turn_off
        data_template:
          entity_id: group.all_lights
      - service: input_boolean.turn_on
        data_template:
          entity_id: input_boolean.security_alarm
      - service: script.all_audio_off
